### ISSUE TITLE
brew formula

### ISSUE THREAD

**Issue by Raikerian** [narugit/smctemp#3]
Hey, thanks for this binary. Any chance you can set up brew formula for this?

**Comment by narugit** [comment]
@Raikerian 
Hi, sorry for late response. 
Yes. I want to add this tool in brew formula. However, I have never added tools in brew formula, so I need to investigate how to do.
Any supports are welcome :)

**Comment by mikemimik** [comment]
@narugit I was looking to see what requirements exist to create a brew formula and there are some good documents that exist for it.

<img width="649" alt="image" src="https://user-images.githubusercontent.com/2818462/236989586-416721b0-8b71-411f-858e-994a77cac6ad.png">

I'd be happy to contribute a github workflow that does the versioning and release asset creation for you _(I've done this before for some personal/work projects)_. Once that is in place, we could run the `brew create` command, along with some others, to create the contribution to the homebrew formula json.

> _(It might also be possible to create a github action to also do this homebrew formula update in an automatic way, so that any time a new version is created a new release/asset is created as well as a PR into the homebrew/core repository 🤔)_.

Reference: https://docs.brew.sh/Formula-Cookbook

**Comment by narugit** [comment]
@mikemimik 
Thank you for helpful infomation and strong support!
Is following step is correct to publish as homebrew official package?
1. Create tarball
2. Create formula until audit and test pass
3. Create a pull request to official homebrew repository

I am curious about your workflow.
Could you create a pull request in this repository to add workflow?

**Comment by jvhaarst** [comment]
What @mikemimik means is that he can help you with setting up a workflow to create versioned releases of your code, thus checking off the "has a stable, tagged version" bullet in the requirements.

**Comment by jvhaarst** [comment]
On the main page of your repo you will find a "Releases" section, click on "Create a new release", and then you can tag the current state or a previous commit as a version.

**Comment by narugit** [comment]
@jvhaarst 
Sorry for late response. I will ready to get started.

**Comment by narugit** [comment]
## Tasks
Ref.: https://docs.brew.sh/Formula-Cookbook
- [ ] meets all our Acceptable Formulae requirements
- [ ] isn’t already in Homebrew (check brew search <formula>)
- [ ] isn’t already waiting to be merged (check the issue tracker)
- [ ] is still supported by upstream (i.e. doesn’t require extensive patching)
- [ ] has a stable, tagged version (i.e. isn’t just a GitHub repository with no versions)
- [ ] passes all brew audit --new-formula <formula> tests
- [ ] Before submitting a new formula make sure you read over our contribution guidelines.

**Comment by narugit** [comment]
> - [x] isn’t already in Homebrew (check brew search <formula>)

```console
$ brew search smctemp
Error: No formulae or casks found for "smctemp".
```

**Comment by narugit** [comment]
> - [x] isn’t already waiting to be merged (check the issue tracker)

Yes. This is the first time.

**Comment by jvhaarst** [comment]
Hi, do you need help with this ?
The main thing (without that nobody would be able to test locally), is to create a release.
You could just create a release of only the latest, or go back through the commits, and decide how big a change it was, and whether it was a change big enough to make it a new version.
Some ideas are here : https://nehckl0.medium.com/semver-and-calver-2-popular-software-versioning-schemes-96be80efe36
In the end it is your project, and you can decide how to version it.
But brew apparently needs and wants a version, so you will have to create a release, and add a version to it.

**Comment by narugit** [comment]
@jvhaarst 
Thank you for kind support! May I ask a question?
Actually I am trying to write GitHub Actions workflow in [.github/workflows/release.yml](https://github.com/narugit/smctemp/blob/feature/add_workflow_to_release/.github/workflows/release.yml) to create a release, but I have no idea to build each binary for x86_64 and arm64 with GitHub Actions.
Do I need to build by two binaries by myself and upload to release manually?

**Comment by jvhaarst** [comment]
I just had a look, and I couldn't find a way to compile arm64 from github actions, using the macos-latest runner (more info at https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners)

I did succeed in getting brew to create a functioning smctemp locally:

1. Create a release (click on [Release](https://github.com/narugit/smctemp/releases), and follow the steps)
2. `brew create  [URL of release tar.gz]`, and change the recipe (see below)
3. `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source --verbose --debug smctemp`
4. `brew audit --strict --online smctemp`
5. After that you will have to follow the cookbook on how to add it to te brew recipe repo.
(in the below code I have changed the test to use version as a variable, so make sure the version you publish is the same as referenced in the code)
smtemp.rb:
```
class Smctemp < Formula
  desc "Check Temperature by using Apple System Management Control (Smc) tool"
  homepage "https://github.com/narugit/smctemp"
  url "https://github.com/narugit/smctemp/archive/refs/tags/v0.1.tar.gz"
  sha256 "986b2c1e8d6452a9f57342bf440e7bdbecf07983ce62dacfbe3fdcad0345f313"
  license "GPL-2.0-only"

  depends_on :macos

  def install
    system "make"
    bin.install "smctemp"
  end

  test do
    assert_match "#{version}", shell_output("#{bin}/smctemp -v")
  end
end
```

**Comment by jvhaarst** [comment]
The test is better written like this, otherwise you will get a warning : 
```
  test do
    assert_match version.to_s, shell_output("#{bin}/smctemp -v")
  end
```

And a HEAD section would also be nice.

**Comment by narugit** [comment]
@jvhaarst 
Thank you!!
I have just created the release [0.1.0](https://github.com/narugit/smctemp/releases/tag/0.1.0).
Now I'm trying to execute step 2.

By the way, do I need to support `x86_64 Linux` to publish in https://github.com/Homebrew/homebrew-core?
https://docs.brew.sh/Acceptable-Formulae#supported-platforms

**Comment by jvhaarst** [comment]
You can try to limit it to only arm64, see https://docs.brew.sh/Cask-Cookbook#depends_on-arch
And then just see what happens.

**Comment by narugit** [comment]
@jvhaarst 
Your link is for "Cask", so do you mean that I should upload to [homebrew-core](https://github.com/Homebrew/homebrew-core) not [homebrew-core](https://github.com/Homebrew/homebrew-core)?

I suppose that smctemp is buildable from source code, so I want to upload to [homebrew-core](https://github.com/Homebrew/homebrew-core).
However I suppose that I have to support Linux to upload to homebrew-core from https://docs.brew.sh/Acceptable-Formulae#supported-platforms, but smctemp is only for macOS, so is it not available to upload to homebrew-core?
> The formula needs to build and pass tests on the latest 3 supported macOS versions ([x86_64 and Apple Silicon/ARM](https://docs.brew.sh/Installation#macos-requirements)) and on x86_64 [Linux](https://docs.brew.sh/Linux-CI).

**Comment by jvhaarst** [comment]
In my recipe above, I have   `depends_on :macos` ,  so that would mean it won't be available for Linux.
I would just try to release it with that limit, and see whether or not the maintainer lets it pass.
[This](https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/osx-cpu-temp.rb) recipe also only allows macos, so I don't think it will be a problem.

**Comment by narugit** [comment]
I'm now starting to create pull request to homebrew-core.
ref. https://docs.brew.sh/How-To-Open-a-Homebrew-Pull-Request#formulae-related-pull-request

**Comment by narugit** [comment]
I've created workflow to create release: https://github.com/narugit/smctemp/blob/main/.github/workflows/release.yml

**Comment by narugit** [comment]
## Step to release
1. Create release by https://github.com/narugit/smctemp/blob/main/.github/workflows/release.yml
2. `brew create --set-name=smctemp https://github.com/narugit/smctemp/archive/refs/tags/[tag name].tar.gz`
3. Modify smctemp.rb
4. Follow https://docs.brew.sh/How-To-Open-a-Homebrew-Pull-Request#formulae-related-pull-request
5. Follow https://docs.brew.sh/How-To-Open-a-Homebrew-Pull-Request#create-your-pull-request-from-a-new-branch

**Comment by narugit** [comment]
@jvhaarst 
Finally I've created pull request on https://github.com/Homebrew/homebrew-core/pull/138800.
Thank you for your full support!

However, I've failed below, so this repository seems to become more popular...
```console
$ brew audit --new smctemp
smctemp
  * GitHub repository not notable enough (<30 forks, <30 watchers and <75 stars)
Error: 1 problem in 1 formula detected.
```

**Comment by narugit** [comment]
> However, I've failed below, so this repository seems to become more popular...

In homebrew-core CI, same failure has occurred(
https://github.com/Homebrew/homebrew-core/actions/runs/5776153126/job/15655000769
```
==> brew audit smctemp --online --new-formula
==> FAILED
Full audit smctemp --online --new-formula output
  smctemp
    * GitHub repository not notable enough (<30 forks, <30 watchers and <75 stars)
  Error: 1 problem in 1 formula detected.
```

**Comment by narugit** [comment]
Hi @Raikerian @jvhaarst @joshuataylor @kaskavalci @yllekz @mikemimik 

Thanks for the interest in my repo! I'd love to have it on Homebrew, but currently, the project needs more notability (Forks, Stars, Watches) to meet the Homebrew criteria.

If you could help by spreading the word to your network or anyone who might find it useful, that would be amazing! Your support could make a big difference.

Thanks again for considering it!

**Comment by joshuataylor** [comment]
Would it be worth setting this up as a [Cask](https://github.com/Homebrew/homebrew-cask) / https://docs.brew.sh/Adding-Software-to-Homebrew?

A few apps I use does this (macfuse, wezterm, filezilla, imageoptim, vorta from a quick peek at my shell history :)).

**Comment by narugit** [comment]
@joshuataylor 
Thank you for the information.

From https://docs.brew.sh/Acceptable-Casks#rejected-casks, It seems that my repository will be rejected..
> App is too obscure. Examples:
> An app from a code repository that is not notable enough (under 30 forks, 30 watchers, 75 stars).

**Comment by joshuataylor** [comment]
Ah bummer. It's a super useful project, as it's *FAST AF*.

I use it in my tmux window, as I have to check for OS and use either this or sensors on Linux. I only care about Apple Silicon macs and Linux though :).

--

I think it might be worthwhile to also setup GH Actions to build the project for easier installation. When I have time in the next couple of days I'll submit this as a PR, as multi-arch builds with GH Actions are tedious at best :).

**Comment by vaygr** [comment]
I would recommend, while notability is still a problem, to establish your personal tap and keep the formula there. See [How to Create and Maintain a Tap](https://docs.brew.sh/How-to-Create-and-Maintain-a-Tap) and https://github.com/vaygr/homebrew-tap re: what it looks like.

This way you can announce installation method in the README like so:

```shell
brew install narugit/tap/smctemp
```

Once notability is not an issue, you can re-submit the original PR and add `smctemp` to [autobump.txt](https://github.com/Homebrew/homebrew-core/blob/master/.github/autobump.txt). Within a couple of hours of new releases it'll be auto-submitted and released in Homebrew. No need to set up pipelines for PR submission on your end.

**Comment by narugit** [comment]
Hi @vaygr 
Thanks so much for the tip! I’ve just set up my personal Homebrew tap and added the smctemp formula:

Repository: https://github.com/narugit/homebrew-tap

I've added README to install smctemp by using brew tap.
https://github.com/narugit/smctemp/pull/43

Once smctemp gains enough traction, I’ll re-submit the PR to Homebrew/homebrew-core
Thank you again for your guidance!

**Comment by narugit** [comment]
Retry on https://github.com/Homebrew/homebrew-core/pull/278967

**Comment by narugit** [comment]
Failed with new criteria
```
Full audit --formula smctemp --online --new output
  smctemp
    * Self-submitted GitHub repository not notable enough (<90 forks, <90 watchers and <225 stars)
  Error: 1 problem in 1 formula detected.
```

It looks like the notability requirements for self-submitted repositories have become stricter than I expected.

https://docs.brew.sh/Acceptable-Formulae#niche-or-self-submitted-stuff
> - be known (e.g. GitHub repositories should have >=30 forks, >=30 watchers or >=75 stars)
>   - notability requirements for self-submitted software are 3 times higher than the applicable thresholds above (e.g. on GitHub: >=90 forks, >=90 watchers, or >=225 stars)
